
import os.path

Import("env")


# SOURCES

tasksources = [

	'task.c'

	]

networkheaders = [

	'build.h', 'hashstrings.h', 'internal.h', 'task.h', 'types.h'

	]


# ADD INTERNAL FLAGS

libenv = env.Clone()
libenv.Append( CPPDEFINES=['TASK_COMPILE=1'] )


# OUTPUTS

env['tasklib'] = libenv.StaticLibrary( 'task', tasksources )


# DEPENDENCIES

#if env['toolset'] == 'gnu':
#	libenv.Depends( [ os.path.splitext( x )[0] + '.o' for x in tasksources ], '#/task/task.h.gch' )


# INSTALLS

libenv.AddPostAction( 'task', libenv.Install( '#lib/${platform}${platformsuffix}/${buildprofile}', [ env['tasklib'] ] ) )
